name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

jobs:
  build:
    name: "Check Gradle Build"
    runs-on: ubuntu-latest
    steps:
      - name: (Set Up) checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: Update Git submodules
        run: git submodule update --remote --recursive

      - name: (Set Up) Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: (Set Up) Grant Execute permission for gradlew
        run: chmod 777 gradlew

      - name: (Build) Build with Gradle
        run: ./gradlew clean build -i
